//go:build !ignore_autogenerated

/*
Copyright 2025 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerLevel) DeepCopyInto(out *PowerLevel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerLevel.
func (in *PowerLevel) DeepCopy() *PowerLevel {
	if in == nil {
		return nil
	}
	out := new(PowerLevel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PowerLevel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerLevelList) DeepCopyInto(out *PowerLevelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PowerLevel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerLevelList.
func (in *PowerLevelList) DeepCopy() *PowerLevelList {
	if in == nil {
		return nil
	}
	out := new(PowerLevelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PowerLevelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerLevelObservation) DeepCopyInto(out *PowerLevelObservation) {
	*out = *in
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Events != nil {
		in, out := &in.Events, &out.Events
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LastModified != nil {
		in, out := &in.LastModified, &out.LastModified
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerLevelObservation.
func (in *PowerLevelObservation) DeepCopy() *PowerLevelObservation {
	if in == nil {
		return nil
	}
	out := new(PowerLevelObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerLevelParameters) DeepCopyInto(out *PowerLevelParameters) {
	*out = *in
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Events != nil {
		in, out := &in.Events, &out.Events
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.EventsDefault != nil {
		in, out := &in.EventsDefault, &out.EventsDefault
		*out = new(int)
		**out = **in
	}
	if in.StateDefault != nil {
		in, out := &in.StateDefault, &out.StateDefault
		*out = new(int)
		**out = **in
	}
	if in.UsersDefault != nil {
		in, out := &in.UsersDefault, &out.UsersDefault
		*out = new(int)
		**out = **in
	}
	if in.Ban != nil {
		in, out := &in.Ban, &out.Ban
		*out = new(int)
		**out = **in
	}
	if in.Kick != nil {
		in, out := &in.Kick, &out.Kick
		*out = new(int)
		**out = **in
	}
	if in.Redact != nil {
		in, out := &in.Redact, &out.Redact
		*out = new(int)
		**out = **in
	}
	if in.Invite != nil {
		in, out := &in.Invite, &out.Invite
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerLevelParameters.
func (in *PowerLevelParameters) DeepCopy() *PowerLevelParameters {
	if in == nil {
		return nil
	}
	out := new(PowerLevelParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerLevelSpec) DeepCopyInto(out *PowerLevelSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerLevelSpec.
func (in *PowerLevelSpec) DeepCopy() *PowerLevelSpec {
	if in == nil {
		return nil
	}
	out := new(PowerLevelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerLevelStatus) DeepCopyInto(out *PowerLevelStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerLevelStatus.
func (in *PowerLevelStatus) DeepCopy() *PowerLevelStatus {
	if in == nil {
		return nil
	}
	out := new(PowerLevelStatus)
	in.DeepCopyInto(out)
	return out
}
